### ISSUE TITLE
click on load for current file the Gyroflow application opens by itself

### ISSUE THREAD

**Issue by AlphaBeta2A** [gyroflow/gyroflow-ofx#65]
I've just reinstalled Davinci Resolve Studio on my PC, installed the plugin as indicated, but when I click on load for current file to stabilize the video, it opens the Gyroflow application in another window (as if I were using the Gyroflow application to stabilize the video).
I didn't have this problem before on my previous PC.
I've also tried it on my MAC, and I have the same problem.

If anyone has a solution please?

Thanks a lot!

**Comment by AdrianEddy** [comment]
It should be already fixed in the dev build of the plugin https://gyroflow.xyz/devbuild

**Comment by AlphaBeta2A** [comment]
Thanks for the reply! I just tried downloading the OPEN FX Plugin dev Build, but it didn't change anything, I still have the same problem.

**Comment by AdrianEddy** [comment]
What camera are you using? It usually means that you have to synchronize the video in the app first, then load project file in plugin

**Comment by AlphaBeta2A** [comment]
I use a GOPRO HERO 6 and a GOPRO HERO 12. 
So when the GYROFLOW application opens in another window, I have to stabilize directly in the application and export to DAVINCI RESOLVE STUDIO?
For the example, I dropped the file into DAVINCI, clicked on load for current file and then the GYROFLOW application opened with my stabilized video. 
What should I do next? Click on export? 
![Capture d’écran 2024-07-29 005713](https://github.com/user-attachments/assets/7c8304d7-fee3-482c-be00-cf992d7e936f)

**Comment by AdrianEddy** [comment]
Click Ctrl+S, then go back to plugin and click "Last saved project"

**Comment by AlphaBeta2A** [comment]
Great! Thanks, it worked!
